### ISSUE TITLE
Author data when posting a book

### ISSUE THREAD

**Issue by michellelockett** [CloudMinders/green-field#25]
if the book is new, we get author data back.  If the book is already in the DB, we don't get author info back.

**Comment by michellelockett** [comment]
<img width="921" alt="screen shot 2018-02-28 at 3 35 30 pm" src="https://user-images.githubusercontent.com/19374552/36819179-20ffbfb8-1c9d-11e8-97f1-6152b00d2541.png">

**Comment by michellelockett** [comment]
<img width="937" alt="screen shot 2018-02-28 at 3 36 38 pm" src="https://user-images.githubusercontent.com/19374552/36819196-342cc8c4-1c9d-11e8-8ad6-a6f85a447a19.png">

**Comment by michellelockett** [comment]
how client is expecting data
<img width="390" alt="format needed" src="https://user-images.githubusercontent.com/19374552/36819251-89c56372-1c9d-11e8-9661-383fe2c7d84b.png">

**Comment by rainier-c** [comment]
Can we refactor our expectations on the client side so that `author` becomes array `authors`? Unfortunately we'll have multiple authors sometimes and no way to determine who is primary.

**Comment by michellelockett** [comment]
totally, no problem . I'll take care of that

**Comment by rainier-c** [comment]
As a reach goal though, I think it would be nice if a user could 'select' a primary author when multiple authors appear and our client would re-render accordingly with just that author. What do you think?

**Comment by michellelockett** [comment]
For a POST, we get back author data, but for a GET to users/id none of the books have any associated author data.  I figure that to start I'll just pick the first one on the list.  I like the reach goal!

**Comment by michellelockett** [comment]
I did open a new issue for the POST though
