### ISSUE TITLE
wrong books added

### ISSUE THREAD

**Issue by michellelockett** [CloudMinders/green-field#79]
ISBN: 9781442493285

**Comment by michellelockett** [comment]
When adding multiple books in a row, it returns the previous book's cover

**Comment by michellelockett** [comment]
9781435150010

**Comment by michellelockett** [comment]
I think when it can't find a book, it is sending back the last known cover, and an empty book
<img width="1161" alt="screen shot 2018-03-06 at 5 26 27 pm" src="https://user-images.githubusercontent.com/19374552/37068448-97d163ec-2163-11e8-8091-2aa22baa91e0.png">

**Comment by rainier-c** [comment]
When you say 'multiple books in a row', does that mean manually adding books in quick succession manually? Or were you loading via a helper function?

**Comment by michellelockett** [comment]
manually

**Comment by michellelockett** [comment]
in the case of 9781435150010 google can't find the book.  but it's showing cover info for the last book added

**Comment by michellelockett** [comment]
and that book is getting stored in DB with all null values except ISBN

**Comment by michellelockett** [comment]
and the first book, I had to delete two records in the DB and now it is grabbing all the right info correctly
